### ISSUE TITLE
Support Metamask privacy mode

### ISSUE THREAD

**Issue by raamb** [singnet/alpha-dapp#35]
MetaMask and other dapp browsers will stop exposing user accounts by default. Instead, dapps must request access using a new provider method: provider.enable(). Details -
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Comment by tiero** [comment]
yes, is something where @vforvalerio87 is writing down a plan for a dapp refactor, wich includes this. 

@raamb If you have time can be a good first issue to take on

**Comment by raamb** [comment]
@tiero have created a pull request for this
