### ISSUE TITLE
Deprecating a record on snet-cli doesn't remove it entirely from the daap

### ISSUE THREAD

**Issue by tesYolan** [singnet/alpha-dapp#8]
I unfortunately registered an agent to a wrong ip:port configuration while testing out registering an agent as outlined in the wiki. And hence generating a ip:port config that points to no where to be available on the [dapp](http://alpha.singularitynet.io/)

So to remove the agent from the daap, I invoked the following command, 

`snet registry deprecate-record emotion_recognition`

Afterwards, though it seems that the agent name, address, price and end point had disappeared, it still maintains the `create-job` entry with empty values, which leds to `job` tab when clicked. 

Is there some cache time before that line disappears or another means to deprecate or delete an agent?

**Comment by tesYolan** [comment]
This seems to be an issue with snet-cli/alpha-blockchain as also `snet registry list-records` outputs
```
(emotion-recogntion-snet-agent) $ snet registry list-records
    records:
    -   address: '0x2ED982c220feD6C9374e63804670fc16BD481b8f'
        name: Alpha TensorFlow Agent
    -   address: '0x4cBe33Aa28eBBbFAa7d98Fa1c65af2FEf6885EF2'
        name: face_detect
    -   address: '0x88DeC961e30F973b6DeDbae35754a3c557380BEE'
        name: face_landmarks
    -   address: '0xCB58410EE3B8E99ABd9774aB98951680E637b5F3'
        name: face_alignment
    -   address: '0x8f3c5F4B522803DA8B07a257b6a558f61100452C'
        name: face_recognition
    -   address: '0x0000000000000000000000000000000000000000'
        name: ''
```
Would close this issue when I isolate the on issue on either https://github.com/singnet/alpha-blockchain or https://github.com/singnet/snet-cli

**Comment by erickearns** [comment]
This is an issue with how listRecords currently works

https://github.com/singnet/alpha-blockchain/blob/master/contracts/Registry.sol#L57

We don't shorten the list that's returned, but the apps that use this list can be updated to trim empty entries from the end

**Comment by lcdupree** [comment]
fixed and pushed.
