### ISSUE TITLE
API call response failure

### ISSUE THREAD

**Issue by CJHackerz** [singnet/alpha-dapp#9]
I have been trying to interact with agents on [http://alpha.singularitynet.io](http://alpha.singularitynet.io) after uploading the image file to an agent, it never gets the response from API call and keeps loading on screen forever

![Screenshot](https://i.imgur.com/OIvDLzv.png "Screenshot")

Tested with:
Chrome browser(Version 66.0.3359.181)(64-bit) - Metamask
Brave browser (Version 0.22.727)(64-bit)

Txhash: [0x1d43e74f868962847f23ea5639625ce57a375ea57a54cf4930680ce08f0ec348](https://kovan.etherscan.io/tx/0x1d43e74f868962847f23ea5639625ce57a375ea57a54cf4930680ce08f0ec348)

**Comment by lcdupree** [comment]
Can you please try again? The host behind the Alpha TensorFlow Agent was down temporarily.

**Comment by lcdupree** [comment]
closing this as fixed
